# Generated by Django 5.0.2 on 2024-04-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('network', models.CharField(choices=[('DEVNET', 'Development Network'), ('TESTNET', 'Test Network'), ('MAINNET', 'Main Network')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.chain')),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('token_id', models.CharField(max_length=10)),
                ('image_url', models.URLField()),
                ('smart_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.smartcontract')),
            ],
        ),
    ]
