# Generated by Django 5.0.2 on 2024-04-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('DEVNET', 'DEVNET'), ('TESTNET', 'TESTNET'), ('MAINNET', 'MAINNET')], max_length=50)),
                ('name', models.CharField(choices=[('ETHEREUM', 'ETHEREUM'), ('SOLANA', 'SOLANA')], max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50, unique=True)),
                ('contract_abi_json', models.FileField(blank=True, null=True, upload_to='static/smart_contract_abi')),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('token_id', models.CharField(max_length=10)),
                ('image_url', models.URLField(default='')),
                ('smart_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.smartcontract')),
            ],
            options={
                'unique_together': {('smart_contract', 'token_id')},
            },
        ),
    ]
