# Generated by Django 5.0.2 on 2024-04-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='name',
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='contract_abi_json',
            field=models.FileField(blank=True, null=True, upload_to='static/smart_contract_abi'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
