# Generated by Django 5.0.2 on 2024-04-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_remove_nft_name_smartcontract_contract_abi_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='address',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
