# Generated by Django 5.0.2 on 2024-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_rename_name_smartcontract_chain_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcontract',
            name='name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
