# Generated by Django 5.0.2 on 2024-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_smartcontract_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontract',
            old_name='code',
            new_name='uri',
        ),
        migrations.RemoveField(
            model_name='smartcontract',
            name='contract_abi_json',
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='abi',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
