# Generated by Django 5.0.2 on 2024-04-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_smartcontract_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nft',
            unique_together={('smart_contract', 'token_id')},
        ),
    ]
