# Generated by Django 5.0.2 on 2024-04-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_rename_code_smartcontract_uri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartcontract',
            name='chain_name',
        ),
        migrations.RemoveField(
            model_name='smartcontract',
            name='uri',
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='blockchain',
            field=models.CharField(choices=[('ETHEREUM', 'ETHEREUM'), ('SOLANA', 'SOLANA')], default='ETHEREUM', max_length=50),
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='token_symbol',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='network',
            field=models.CharField(choices=[('DEVNET', 'DEVNET'), ('TESTNET', 'TESTNET'), ('MAINNET', 'MAINNET')], default='MAINNET', max_length=50),
        ),
    ]
