# Generated by Django 5.0.4 on 2024-04-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_remove_smartcontract_chain_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcontract',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
