# Generated by Django 5.0.2 on 2024-04-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_smartcontract_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('ETHEREUM', 'ETHEREUM'), ('SOLANA', 'SOLANA'), ('POLYGON', 'POLYGON')], default='ETHEREUM', max_length=50)),
                ('network', models.CharField(choices=[('MAINNET', 'MAINNET'), ('TESTNET', 'TESTNET'), ('DEVNET', 'DEVNET')], default='MAINNET', max_length=50)),
                ('rpc_server', models.URLField()),
                ('image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='smartcontract',
            name='blockchain',
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.network'),
        ),
    ]
