# Generated by Django 5.0.2 on 2024-04-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_network_remove_smartcontract_blockchain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='blockchain',
            new_name='network_name',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='network',
            new_name='network_type',
        ),
    ]
